#!/bin/sh
# Keep the fifo being opened several hours.

fifo=/tmp/bky-led-fifo

# Create the fifo if not exist.
if [ ! -p "$fifo" ]; then
  mkfifo "$fifo"
fi
if [ ! -p "$fifo" ]; then
  echo "Error: cannot create a fifo '$fifo'" 1>&2
  exit 1
fi

# Keep the fifo being opened.
sleep 30000 >"$fifo" &
echo "Success: a background process (pid=$!) has been launched."
